@startuml
actor Accountant
participant HomePage
participant projectController
database Database

== Log in User ==
Accountant -> HomePage : Click "Download File"
HomePage -> projectController : GET /getExcelFile/:file_ID

projectController -> Database : Fetch data (Bill, Invoice, PO)
Database --> projectController : Return data
projectController -> projectController : Generate Excel file
projectController --> HomePage : Download Excel file
HomePage -> Accountant : Save file to device

== Guest ==
Accountant -> HomePage : Click "Download File"
HomePage -> projectController : GET /getExcelFileGuest/:file_ID

projectController -> Database : Fetch data by file_ID
Database --> projectController : Return data
projectController -> projectController : Generate Excel file
projectController --> HomePage : Download Excel file
HomePage -> Accountant : Save file to device

projectController -> Database : DELETE Bill/Invoice/PO/Project
Database --> projectController : Deletion complete
@enduml